name: sentinel
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.8
  - pip=20.3.1
  - affine=2.3.0
  - gdal=3.1.2
  - scipy=1.6.2
  - pip:
    - requests==2.31.0
    - shapely==2.0.2
    - pandas==2.0.2
    - fiona==1.9.5
    - geojson==2.5.0
    - numpy==1.24.4
    - opencv-python==4.4.0.42
    - pyproj==3.5.0
    - rasterio==1.3.9
    - rioxarray==0.13.4
    - tqdm==4.66.1
